In [1]:
import random
import datetime
from dataclasses import dataclass
from typing import List, Dict, Tuple, Sequence, Callable

In [8]:
import numpy as np

In [145]:
@dataclass
class Chromosome:
    genes   : List
    fitness : float

def generate_parent(length: int, geneSet: Sequence, get_fitness: Callable)->Chromosome:
    genes = []
    while len(genes) < length:
        sampleSize = min(length - len(genes), len(geneSet))
        genes.extend(random.sample(geneSet, sampleSize))
    fitness = get_fitness(genes)
    return Chromosome(genes, fitness)

def mutate_genes(genes: List, geneSet: List)->List:
    """Mutate genes target choosing character from geneSet"""

    mutatedGenes         = genes[:]
    index                = random.randrange(0, len(mutatedGenes))
    newGene, alternate   = random.sample(geneSet, 2)
    mutatedGenes[index]  = alternate if newGene == mutatedGenes[index] else newGene
    return mutatedGenes


def mutate_chromosome(geneSet:     Sequence,
                      parent:      Chromosome,
                      get_fitness: Callable)->Chromosome:
    """Generate a mutated chromosome"""
    mutatedGenes = mutate_genes(parent.genes, geneSet)
    fitness      = get_fitness(mutatedGenes)
    return Chromosome(mutatedGenes, fitness)



In [10]:
def dummy(genes):
    return 1

In [90]:
genes = np.arange(8)

In [91]:
genes

array([0, 1, 2, 3, 4, 5, 6, 7])

In [105]:
halfBoard = int(8/2)  
print(halfBoard)
lastBoard = len(genes)
print(lastBoard)
print(genes[0:halfBoard])
print(genes[halfBoard:lastBoard])
for i, j in zip(genes[0:halfBoard], genes[halfBoard:lastBoard]):
    print(i,j)

4
8
[0 1 2 3]
[4 5 6 7]
0 4
1 5
2 6
3 7


In [163]:
@dataclass
class Board:
    genes       : List

    def __post_init__(self):
        
        self.sizeBoard = int(len(self.genes)/2) 
        #print(self.genes)
        #print(self.sizeBoard)
        self.board = self.define_board(self.genes, self.sizeBoard)

    def define_board(self, genes: List, sizeBoard: int)->np.array:
        x = np.arange(sizeBoard * sizeBoard)
        x = x.reshape(sizeBoard,  sizeBoard)
        board = np.zeros_like(x)
        #print(board)
        
        for i, j in zip(genes[0:sizeBoard], genes[sizeBoard: 2 * sizeBoard]):
           
            row = genes[i]
            column = genes[j]
            #print(row, column)
            board[column][row] = 1
        return board

    def display_board(self):
        print(self.board)

In [164]:
sizeBoard = 8
geneSet = [i for i in range(sizeBoard)]
print(geneSet)

[0, 1, 2, 3, 4, 5, 6, 7]


In [165]:
c1 = generate_parent(2*sizeBoard, geneSet, dummy)
print(c1)

Chromosome(genes=[2, 0, 5, 6, 1, 3, 4, 7, 0, 1, 7, 6, 3, 2, 5, 4], fitness=1)


In [166]:
b = Board(c1.genes)

In [167]:
b

Board(genes=[2, 0, 5, 6, 1, 3, 4, 7, 0, 1, 7, 6, 3, 2, 5, 4])

In [168]:
b.display_board()

[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


In [221]:
def get_fitness_verbose(genes):
    def partial_fitness(size, mset):
        return size - len(mset)
    
    board = Board(genes)
    
    board.display_board()
    size  = board.sizeBoard
    rQ = set()
    cQ = set()
    nDQ = set()
    sDQ = set()
    print(f'size = {size}')
    print (f' in {[0,2]}, found {b.board[0,2]}')
    print (f' in {[1,7]}, found {b.board[1,7]}')
    print (f' in {[2,5]}, found {b.board[2,5]}')
    print (f' in {[3,1]}, found {b.board[3,1]}')
    print (f' in {[4,4]}, found {b.board[4,4]}')
    print (f' in {[5,6]}, found {b.board[5,6]}')
    print (f' in {[6,0]}, found {b.board[6,0]}')
    print (f' in {[7,3]}, found {b.board[7,3]}')
    for row in range(size):
        for col in range(size):
            #print(row, col)
            if b.board[row,col] == 1:
                print(f'found Queen at {[row, col]}')
                rQ .add(row)
                cQ .add(col)
                nDQ.add(row + col)
                sDQ.add(size - 1 - row + col)
    print(f'rows with Queen = {rQ} ')
    print(f'cols with Queen = {cQ}')
    print(f'ndia with Queen = {nDQ}')
    print(f'sdia with Queen = {sDQ}' )
                
    total = partial_fitness(size,rQ) + partial_fitness(size, cQ) + partial_fitness(size, nDQ) + partial_fitness(size, sDQ)
    
    print(total)
            
    return 4 * size - total 


In [218]:
get_fitness_verbose(b.genes)

[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]
size = 8
 in [0, 2], found 1
 in [1, 7], found 1
 in [2, 5], found 1
 in [3, 1], found 1
 in [4, 4], found 1
 in [5, 6], found 1
 in [6, 0], found 1
 in [7, 3], found 1
found Queen at [0, 2]
found Queen at [1, 7]
found Queen at [2, 5]
found Queen at [3, 1]
found Queen at [4, 4]
found Queen at [5, 6]
found Queen at [6, 0]
found Queen at [7, 3]
rows with Queen = {0, 1, 2, 3, 4, 5, 6, 7} 
cols with Queen = {0, 1, 2, 3, 4, 5, 6, 7}
ndia with Queen = {2, 4, 6, 7, 8, 10, 11}
sdia with Queen = {1, 3, 5, 7, 8, 9, 10, 13}
1


31

In [226]:
def get_fitness(genes):
    def partial_fitness(size, mset):
        return size - len(mset)
    
    board = Board(genes)
    
    #board.display_board()
    size  = board.sizeBoard
    rQ = set()
    cQ = set()
    nDQ = set()
    sDQ = set()
    
    for row in range(size):
        for col in range(size):
            #print(row, col)
            if b.board[row,col] == 1:
                #print(f'found Queen at {[row, col]}')
                rQ .add(row)
                cQ .add(col)
                nDQ.add(row + col)
                sDQ.add(size - 1 - row + col)
    #print(f'rows with Queen = {rQ} ')
    #print(f'cols with Queen = {cQ}')
    #print(f'ndia with Queen = {nDQ}')
    #print(f'sdia with Queen = {sDQ}' )
                
    total = partial_fitness(size,rQ) + partial_fitness(size, cQ) + partial_fitness(size, nDQ) + partial_fitness(size, sDQ)
    
    #print(total)
            
    return 4 * size - total 


In [227]:
get_fitness(b.genes)

31

In [185]:
optimalFitness = 4 * sizeBoard -1
print(optimalFitness)

31


In [133]:
def compare_fitness(fitness, optimalFitness):
    return fitness > optimalFitness

In [193]:
def optimize(sizeBoard, geneSet, get_fitness, compare_fitness, optimalFitness, verbose=True, imax=10000):
    startTime = datetime.datetime.now()
    random.seed()
    guess = generate_parent(2*sizeBoard, geneSet, get_fitness)
    print(f'First guess = {guess}')

    
    i = 0
    while compare_fitness(guess.fitness, optimalFitness) == False and i < imax:
        newGuess = mutate_chromosome(geneSet, guess, get_fitness)
        print(newGuess)
        time = startTime - datetime.datetime.now()
        if compare_fitness(newGuess.fitness, guess.fitness) == True:
            if verbose:
                print(f'new guess increased fitness: {newGuess}, i = {i}, time = {time}')
            guess = Chromosome(newGuess.genes, newGuess.fitness)
        
        i+=1
    return i, time, guess
    
 

In [194]:
sizeBoard = 8
geneSet = [i for i in range(sizeBoard)]
print(geneSet)

[0, 1, 2, 3, 4, 5, 6, 7]


In [230]:
i, time, solve = optimize(sizeBoard, geneSet, get_fitness, compare_fitness, optimalFitness, verbose=True, imax=10)

First guess = Chromosome(genes=[1, 6, 0, 2, 7, 3, 5, 4, 3, 7, 2, 1, 0, 4, 6, 5], fitness=31)
Chromosome(genes=[1, 6, 0, 2, 7, 3, 5, 4, 3, 6, 2, 1, 0, 4, 6, 5], fitness=31)
Chromosome(genes=[0, 6, 0, 2, 7, 3, 5, 4, 3, 7, 2, 1, 0, 4, 6, 5], fitness=31)
Chromosome(genes=[1, 6, 0, 2, 7, 3, 5, 4, 3, 7, 2, 1, 0, 0, 6, 5], fitness=31)
Chromosome(genes=[1, 6, 0, 2, 7, 3, 5, 4, 0, 7, 2, 1, 0, 4, 6, 5], fitness=31)
Chromosome(genes=[1, 6, 0, 2, 7, 3, 5, 4, 3, 4, 2, 1, 0, 4, 6, 5], fitness=31)
Chromosome(genes=[1, 6, 0, 2, 7, 3, 5, 4, 3, 7, 2, 1, 0, 4, 6, 1], fitness=31)
Chromosome(genes=[1, 6, 0, 2, 7, 3, 5, 4, 3, 7, 2, 1, 7, 4, 6, 5], fitness=31)
Chromosome(genes=[1, 6, 0, 2, 7, 3, 2, 4, 3, 7, 2, 1, 0, 4, 6, 5], fitness=31)
Chromosome(genes=[1, 6, 0, 2, 7, 3, 5, 4, 3, 7, 2, 1, 0, 4, 6, 2], fitness=31)
Chromosome(genes=[1, 1, 0, 2, 7, 3, 5, 4, 3, 7, 2, 1, 0, 4, 6, 5], fitness=31)


In [191]:
print(i)

10000


In [192]:
print(solve)

Chromosome(genes=[1, 7, 5, 3, 4, 6, 2, 0, 5, 2, 0, 4, 1, 7, 3, 6], fitness=24)
