In [1]:
import random
import datetime
from dataclasses import dataclass
from typing import List, Dict, Tuple, Sequence, Callable

In [2]:
import numpy as np

In [3]:
@dataclass
class Chromosome:
    genes   : List
    fitness : float

def generate_parent(length: int, geneSet: Sequence, get_fitness: Callable)->Chromosome:
    genes = []
    while len(genes) < length:
        sampleSize = min(length - len(genes), len(geneSet))
        genes.extend(random.sample(geneSet, sampleSize))
    fitness = get_fitness(genes)
    return Chromosome(genes, fitness)

def mutate_genes(genes: List, geneSet: List)->List:
    """Mutate genes target choosing character from geneSet"""

    mutatedGenes         = genes[:]
    index                = random.randrange(0, len(mutatedGenes))
    newGene, alternate   = random.sample(geneSet, 2)
    mutatedGenes[index]  = alternate if newGene == mutatedGenes[index] else newGene
    return mutatedGenes


def mutate_chromosome(geneSet:     Sequence,
                      parent:      Chromosome,
                      get_fitness: Callable)->Chromosome:
    """Generate a mutated chromosome"""
    mutatedGenes = mutate_genes(parent.genes, geneSet)
    fitness      = get_fitness(mutatedGenes)
    return Chromosome(mutatedGenes, fitness)



In [4]:
def dummy(genes):
    return 1

In [6]:
@dataclass
class Board:
    genes       : List

    def __post_init__(self):
        
        self.sizeBoard = int(len(self.genes)) 
        #print(self.genes)
        #print(self.sizeBoard)
        self.board = self.define_board(self.genes, self.sizeBoard)

    def define_board(self, genes: List, sizeBoard: int)->np.array:
        x = np.arange(sizeBoard * sizeBoard)
        x = x.reshape(sizeBoard,  sizeBoard)
        board = np.zeros_like(x)
        
        R = np.arange(0, sizeBoard)
        for i in np.arange(0, sizeBoard):
           
            column = genes[i]
            row = R[i]
            #print(row, column)
            board[row][column] = 1
        return board

    def display_board(self):
        print(self.board)

In [7]:
sizeBoard = 8
geneSet = [i for i in range(sizeBoard)]
print(geneSet)

[0, 1, 2, 3, 4, 5, 6, 7]


In [8]:
c1 = generate_parent(sizeBoard, geneSet, dummy)
print(c1)

Chromosome(genes=[1, 6, 2, 0, 4, 5, 3, 7], fitness=1)


In [9]:
b = Board(c1.genes)

In [10]:
b

Board(genes=[1, 6, 2, 0, 4, 5, 3, 7])

In [11]:
b.display_board()

[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1]]


In [12]:
geneTest = np.arange(8)
geneTest

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
bTest = Board(geneTest)

In [14]:
bTest.display_board()

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [15]:
bTest

Board(genes=array([0, 1, 2, 3, 4, 5, 6, 7]))

In [16]:
bTest.genes

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
bTest.board

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [18]:
bTest.board[0,0]

1

In [28]:
def test_board_diagonal():
    counter = 0
    geneTest = np.arange(8)
    bTest = Board(geneTest)
    bTest.display_board()
    for i,j in list(zip(np.arange(8), np.arange(8))):
        if bTest.board[i,j] == 1:
            counter += 1
        else:
            return False
        if counter == 8:
            return True
        

In [29]:
test_board_diagonal()

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


True

In [32]:
def test_board_row():
    geneTest = 8*[0]
    bTest = Board(geneTest)
    bTest.display_board()
    counter = 0
    for i,j in list(zip(np.arange(8), np.arange(8))):
        if bTest.board[i,0] == 1:
            counter += 1
        else:
            return False
        if counter == 8:
            return True

In [33]:
test_board_row()

[[1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


True

In [34]:
def get_fitness_verbose(genes):
    def partial_fitness(size, mset):
        return size - len(mset)
    
    b = Board(genes)
    
    b.display_board()
    size  = b.sizeBoard
    rQ = set()
    cQ = set()
    nDQ = set()
    sDQ = set()
    
    for row in range(size):
        for col in range(size):
            #print(row, col)
            if b.board[row,col] == 1:
                print(f'found Queen at {[row, col]}')
                rQ .add(row)
                cQ .add(col)
                nDQ.add(row + col)
                sDQ.add(size - 1 - row + col)
    print(f'rows with Queen = {rQ} ')
    print(f'cols with Queen = {cQ}')
    print(f'ndia with Queen = {nDQ}')
    print(f'sdia with Queen = {sDQ}' )
    
    print(f'partial fitness rows with Queen = {partial_fitness(size,rQ)} ')
    print(f'partial fitness cols with Queen = {partial_fitness(size, cQ)}')
    print(f'partial fitness ndia with Queen = {partial_fitness(size, nDQ)}')
    print(f'partial fitness sdia with Queen = {partial_fitness(size, sDQ)}' )


                
    total = partial_fitness(size,rQ) + partial_fitness(size, cQ) + partial_fitness(size, nDQ) + partial_fitness(size, sDQ)
    
    print(total)
            
    return 4 * size - total 


In [36]:
geneTest = np.arange(8)
geneTest

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
get_fitness_verbose(geneTest)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
found Queen at [0, 0]
found Queen at [1, 1]
found Queen at [2, 2]
found Queen at [3, 3]
found Queen at [4, 4]
found Queen at [5, 5]
found Queen at [6, 6]
found Queen at [7, 7]
rows with Queen = {0, 1, 2, 3, 4, 5, 6, 7} 
cols with Queen = {0, 1, 2, 3, 4, 5, 6, 7}
ndia with Queen = {0, 2, 4, 6, 8, 10, 12, 14}
sdia with Queen = {7}
partial fitness rows with Queen = 0 
partial fitness cols with Queen = 0
partial fitness ndia with Queen = 0
partial fitness sdia with Queen = 7
7


25

In [38]:
geneTest2 = np.array([4, 2, 0, 6, 1, 7, 5, 3])

In [39]:
get_fitness_verbose(geneTest2)

[[0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]]
found Queen at [0, 4]
found Queen at [1, 2]
found Queen at [2, 0]
found Queen at [3, 6]
found Queen at [4, 1]
found Queen at [5, 7]
found Queen at [6, 5]
found Queen at [7, 3]
rows with Queen = {0, 1, 2, 3, 4, 5, 6, 7} 
cols with Queen = {0, 1, 2, 3, 4, 5, 6, 7}
ndia with Queen = {2, 3, 4, 5, 9, 10, 11, 12}
sdia with Queen = {3, 4, 5, 6, 8, 9, 10, 11}
partial fitness rows with Queen = 0 
partial fitness cols with Queen = 0
partial fitness ndia with Queen = 0
partial fitness sdia with Queen = 0
0


32

In [40]:
def get_fitness(genes):
    def partial_fitness(size, mset):
        return size - len(mset)
    
    b = Board(genes)
    
    size  = b.sizeBoard
    rQ = set()
    cQ = set()
    nDQ = set()
    sDQ = set()
    
    for row in range(size):
        for col in range(size):
            if b.board[row,col] == 1:
                rQ .add(row)
                cQ .add(col)
                nDQ.add(row + col)
                sDQ.add(size - 1 - col + row)
                
    total = partial_fitness(size,rQ) + partial_fitness(size, cQ) + partial_fitness(size, nDQ) + partial_fitness(size, sDQ)
    
            
    return 4 * size - total 



In [41]:
get_fitness(geneTest2)

32

In [55]:
optimalFitness = 4 * sizeBoard 
print(optimalFitness)

32


In [56]:
def compare_fitness(f1, f2):
    return f1 >= f2

In [63]:
def optimize(sizeBoard, geneSet, get_fitness, compare_fitness, optimalFitness, verbose=True, imax=10000):
    random.seed()
    startTime = datetime.datetime.now()
    guess = generate_parent(sizeBoard, geneSet, get_fitness)
    print(f'First guess = {guess}')

    
    i = 0
    while compare_fitness(guess.fitness, optimalFitness) == False and i < imax:
        newGuess = mutate_chromosome(geneSet, guess, get_fitness)
        #print(newGuess)
        time = startTime - datetime.datetime.now()
        if compare_fitness(newGuess.fitness, guess.fitness) == True:
            if verbose:
                print(f'new guess increased fitness: {newGuess}, i = {i}, time = {time}')
            guess = Chromosome(newGuess.genes, newGuess.fitness)
        
        i+=1
    return i, time, guess
    
 

In [64]:
sizeBoard = 8
geneSet = [i for i in range(sizeBoard)]
print(geneSet)

[0, 1, 2, 3, 4, 5, 6, 7]


In [66]:
i, time, solve = optimize(sizeBoard, geneSet, get_fitness, compare_fitness, optimalFitness, verbose=True, imax=1000)
print(i, time, solve)

First guess = Chromosome(genes=[1, 4, 7, 6, 2, 0, 5, 3], fitness=29)
new guess increased fitness: Chromosome(genes=[1, 4, 7, 5, 2, 0, 5, 3], fitness=30), i = 0, time = -1 day, 23:59:59.999231
new guess increased fitness: Chromosome(genes=[1, 6, 7, 5, 2, 0, 5, 3], fitness=30), i = 1, time = -1 day, 23:59:59.999037
new guess increased fitness: Chromosome(genes=[1, 4, 7, 5, 2, 0, 5, 3], fitness=30), i = 12, time = -1 day, 23:59:59.997199
new guess increased fitness: Chromosome(genes=[1, 4, 7, 0, 2, 0, 5, 3], fitness=30), i = 19, time = -1 day, 23:59:59.994531
new guess increased fitness: Chromosome(genes=[1, 7, 7, 0, 2, 0, 5, 3], fitness=30), i = 23, time = -1 day, 23:59:59.988041
new guess increased fitness: Chromosome(genes=[1, 7, 4, 0, 2, 0, 5, 3], fitness=30), i = 26, time = -1 day, 23:59:59.978666
new guess increased fitness: Chromosome(genes=[1, 7, 4, 0, 2, 0, 6, 3], fitness=30), i = 33, time = -1 day, 23:59:59.977081
new guess increased fitness: Chromosome(genes=[1, 7, 7, 0, 2, 0, 

In [67]:
print(i)

158


In [68]:
print(solve)

Chromosome(genes=[1, 7, 5, 0, 2, 4, 6, 3], fitness=32)
